# Используем базовый образ Node.js
FROM node:20

# Устанавливаем рабочую директорию
WORKDIR /client

# Копируем package.json и package-lock.json для установки зависимостей
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем весь исходный код приложения
COPY . .

# Открываем порт для приложения
EXPOSE ${VITE_PORT}

# Команда для запуска приложения
CMD ["npm", "run", "dev"]