services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '${VITE_PORT}:${VITE_PORT}'
    volumes:
      - ./client/src:/client/src
      - ./client/vite.config.ts:/vite.config.ts
    environment:
      - NODE_ENV=development
